name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Run test
        run: go test -v -coverprofile cover.out ./... | tee test.out
        shell: bash

      - name: Process results
        if: always()
        uses: malaupa/go-test-coverage-summary-action@v3.0.0
        with:
          test_results: "test.out"
          coverage_profile: "cover.out"
          with_archive: true

      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: release
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [jammy] # add others, if same package should be available in many versions
    steps:
      - name: Deploy
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PULL_TOKEN }}
          script: |+
            github.rest.actions.createWorkflowDispatch({
              owner: 'telekom-mms',
              repo: 'linux-apt',
              workflow_id: 'do_pull.yml',
              ref: 'main',
              inputs: {
                repo: 'oc-daemon',
                version: '${{ matrix.version }}',
                tag: '${{ github.ref_name }}'
              }
            });
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
